blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    post_list,
    post_detail,
    comment_added_view,
    post_search
)
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

sitemaps = {'posts': PostSitemap(), }

app_name = 'blog'

urlpatterns = [
    path('create', create_blog_view, name='create'),
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('comment_added',comment_added_view,name='comment_added'),
    path('search/', post_search.as_view(), name='post_search'),

]

mysite/urls.py
"""mysite URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
# from django.contrib.sitemaps.views import sitemap
# from blog.sitemaps import PostSitemap
# from personal.views import home_screen_view

# sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='log'),
    path('must_authenticate_view/', must_authenticate_view,
         name='must_authenticate'),
    path('account/', account_view, name='account'),
    path('', include('blog.urls', namespace='blog')),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),
    # path('home/', home_screen_view, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #f2f2f2;
    }

</style>

templates/snippets/footer.html
{% load blog_tags %}
<style type="text/css">
    .footer{
        min-height: 100px;
    }
</style>





<div class="d-flex flex-row align-items-center footer m-auto">

    <div class="m-auto" id="sidebar">
        <p>{%total_posts%} posts have been posted on this blog.</p>
        <h3>Most commented posts</h3>
        
        
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>

        
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

templates/snippets/header.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style type="text/css">
    @media (min-width: 768px) {
    html {
        font-size: 16px;
        }
    }

    .search-bar{
        max-width: 500px;
        width: 100%;
    }

</style>




<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
    {% if request.user.is_authenticated %}
        <p>Hello,{{request.user.username}}</p>
    {% endif %}
    </h5>
    <div class="search-bar mt-sm-2 mr-2">
        <form method="get" action="{% url 'blog:post_search' %}">
            <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
        </form>

    </div>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'blog:post_list' %}">Blog</a>
            <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'blog:post_list' %}">Blog</a>
            <a class="p-2 text-dark" href="{% url 'log' %}">Login</a>
            <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
        {%endif%}
        
        
    </nav>
</div>

<script type="text/javascript">
    document.getElementById("id_q").value = '{{query}}'
</script>