blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    post_list,
    post_detail,
    comment_added_view,
    post_search
)
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

sitemaps = {'posts': PostSitemap(), }

app_name = 'blog'

urlpatterns = [
    path('create', create_blog_view, name='create'),
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('comment_added',comment_added_view,name='comment_added'),
    path('search/', post_search.as_view(), name='post_search'),

]

mysite/urls.py
"""mysite URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
# from django.contrib.sitemaps.views import sitemap
# from blog.sitemaps import PostSitemap
# from personal.views import home_screen_view

# sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='log'),
    path('must_authenticate_view/', must_authenticate_view,
         name='must_authenticate'),
    path('account/', account_view, name='account'),
    path('', include('blog.urls', namespace='blog')),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),
    # path('home/', home_screen_view, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.conf import settings
from django.utils.text import slugify
from django.dispatch import receiver
from django.db.models.signals import post_delete, pre_save


def upload_location(instance, filename, **kwargs):
    file_path = f'blog/{str(instance.author.id)}/{str(instance.title)}-{filename}'
    return file_path


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_COICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(blank=True, unique=True)
    image = models.ImageField(
        upload_to=upload_location, null=False, blank=False)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField(null=False, blank=False)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_COICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish']


# @receiver(post_delete, sender=Post)
# def submission_delete(sender, instance, **kwargs):
#     instance.image.delete(False)


# def pre_save_blog_post_receiever(sender, instance, **kwargs):
#     if not instance.slug:
#         instance.slug = slugify(instance.author.username+'-'+instance.title)


# pre_save.connect(pre_save_blog_post_receiever, sender=Post)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

# # class like(models.Model()):

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_COICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_COICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
            self.publish.month, self.publish.day, self.slug])
    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post, Comment


class CreateBlogPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image']


class SearchForm(forms.Form):
    query = forms.CharField()


class UpdateBlogPostForm:
    class Meta:
        model = Post
        fields = ['title', 'body', 'image']

        def save(self, commit=True):
            blog_post = self.instace
            blog_post.title = self.cleaned_data['title']
            blog_post.body = self.cleaned_data['body']
            if self.cleaned_data['image']:
                blog_post.image = self.cleaned_data['image ']
            if commit:
                blog_post.save()
            return blog_post 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

mysite/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from blog.forms import CreateBlogPostForm
from account.models import Account
from django.db.models import Q
# from django.views.generic import ListView
# from django.contrib.postgres.search import TrigramSimilarity
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from django.http import HttpResponse
# from django.core.mail import send_mail
from taggit.models import Tag
# from django.db.models import Count
from django.views.generic import TemplateView, ListView


def create_blog_view(request):
    contex = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
    return render(request, 'blog/createblog.html', contex)


class post_search(ListView):
    model = Post
    template_name = 'blog/post/search_results.html'

    def get_queryset(self):  # new
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        )
        return object_list


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if request.GET:
        query = request.GET['q']
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    latest_posts = Post.published.all()[0:3]

    return render(request, 'blog/post/list.html',
                  {
                      'page': page,
                      'posts': posts,
                      'tag': tag,
                      'latest_posts': latest_posts,


                  })


def comment_added_view(request):
    return render(request, 'blog/post/comment_added.html', {})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
            return redirect('blog:comment_added')
    else:
        comment_form = CommentForm()
    # post_tags_ids = post.tags.values_list('id', flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids)\
    #     .exclude(id=post.id)
    # similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
    #     .order_by('-same_tags', '-publish')[:4]
    similar = post.tags.similar_objects()
    return render(request,
                  'blog/post/detail.html', {
                      'post': post,
                      'comments': comments,
                      'new_comment': new_comment,
                      'comment_form': comment_form,
                      'similar_posts': similar,
                      'similar': similar
                  })

mysite/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView
from .forms import EmailPostForm
from django.http import HttpResponse
from django.core.mail import send_mail

def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
   
    # Форма была отправлена на сохранение.
    form = EmailPostForm(request.POST)
    if form.is_valid():
        # Все поля формы прошли валидацию.
        cd = form.cleaned_data
        # ... Отправка электронной почты.
        post_url = request.build_absolute_uri(post.get_absolute_url())
        subject = '{} ({}) recommends you reading "\
            {}"'.format(cd['name'], cd['email'], post.title)
        message = 'Read "{}" at {}\n\n{}\'s comments:\
            {}'.format(post.title, post_url, cd['name'], cd['comments'])
        send_mail(subject, message, 'savichevdenis244@gmail.com', [cd['to']])
        sent = True
        
    else:
        form = EmailPostForm()
        return render(request, 'blog/post/share.html',
                        {'post': post, 'form': form,'sent': sent})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

blog/templates/blog/post/comment_added.html
{% extends "base.html" %}

{% block content %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Well done!</h4>
        </div>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}
<style class="text/css">
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
</style>
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>



    

<div class="container">
    <div class="row">
        <div class="card m-auto">
            <img class="card-image-top" src="{{post.image.url}}">
            <div class="card-body my-2">
            <h2 class="card-title">{{post.title}}</h2>
            <p class="card-text">{{post.body|safe}}</p>
            </div>
            <div class="card-footer text-muted">
                Published {{ post.publish }} by {{ post.author.username }}
            </div>
            <div class="card create-post-bar d-flex flex-column p-3">
                
                {% if not similar %}
                    <p>Have no similar posts</p>
                {% else %}
                    
                <h3>Similar posts:</h3>
                <ul> 
                    {% for post in similar %}
                        <h2>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h2>
                    {% endfor %}
                {%endif%}
                </ul>
            </div>
        </div>
    </div>
</div>
 
   
   

{% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment {{ total_comments|pluralize }}</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
        {% csrf_token %}

        {{ comment_form.as_p }}
        <p><input type="submit" value="Add comment"></p>
    </form>
{% endif %}
        
   
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock %}
{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		background-color: #fff;
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
    .posts{
        max-width: 500px;
        width: 100%;
        margin: auto;
    }
</style>
<h1>My Blog</h1>
{% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<div class="container mt-4 p-4">
    <div class="row">
        <div class="posts">
        <h3 class="mx-auto mb-3 font-weight-normal">Blog posts</h3>
        {% if posts %}             
        <ul>
            {% for post in posts %}
                <h2>
                    <a href="{{ post.get_absolute_url }}" style="text-decoration: none;">
                        <li class="list-group-item"> {{ post.title }}</li></a>
                </h2>
                {{ post.body|markdown|truncatewords:30 }}

                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author.username }}
                </p>
            {% endfor %}
        </ul>
        {% else %}
        <p>There is no posts yet.</p>
        {% endif %}
        </div>
    
            
        <div class="right-column col-lg-3 d-lg-flex d-none flex-column">
        {% if request.user.is_authenticated %}
        <div class="card create-post-bar d-flex flex-column p-3">
            <img class="img-fluid d-block m-auto pb-2" src="{% static 'your-blog-logo-280x224.png' %}" width="72" height="72">
            <p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
                framework and you'll see why in this course.</p>
            <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
        </div>

        <div class="card create-post-bar d-flex flex-column p-3">
            <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
        </div>

        {% else %}
        <div class="card create-post-bar d-flex flex-column p-3">
            <img class="img-fluid d-block m-auto pb-2" src="{% static 'your-blog-logo-280x224.png' %}" width="72" height="72">
            <h3>Latest posts:</h3>
            <ul>
                {% for post in latest_posts %}
                    <p><a  href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                {% endfor %}
            </ul>
        </div>
        
        <div class="card create-post-bar d-flex flex-column p-3">
            <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
        </div>
        {% endif%}
        </div>
        </div>
    </div>
<div class="paginator">
    {% include "pagination.html" with page=posts %}
</div>

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <!-- <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search"> -->
        <!-- </form> -->
    {% endif %}
{% endblock %}

blog/templates/blog/post/search_results.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock %}


<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		background-color: #fff;
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
    .posts{
        max-width: 500px;
        width: 100%;
        margin: auto;
    }
</style>


{% block content %}
{% if object_list %}

  
<h1>Search results</h1>
{% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<div class="container mt-4 p-4">
    <div class="row">
        <div class="posts">
        <h3 class="mx-auto mb-3 font-weight-normal">Blog posts</h3>
        {% if object_list %}             
        <ul>
            {% for post in object_list %}
                <h2>
                    <a href="{{ post.get_absolute_url }}" style="text-decoration: none;">
                        <li class="list-group-item"> {{ post.title }}</li></a>
                </h2>
                {{ post.body|markdown|truncatewords:30 }}

                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author.username }}
                </p>
            {% endfor %}
        </ul>
        {% else %}
        <p>There is no posts yet.</p>
        {% endif %}
        </div>
    
            
        <div class="right-column col-lg-3 d-lg-flex d-none flex-column">
        {% if request.user.is_authenticated and request.user.is_admin %}
        <div class="card create-post-bar d-flex flex-column p-3">
            <img class="img-fluid d-block m-auto pb-2" src="{% static 'your-blog-logo-280x224.png' %}" width="72" height="72">
            <p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
                framework and you'll see why in this course.</p>
            <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
        </div>

        <div class="card create-post-bar d-flex flex-column p-3">
            <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
        </div>

        {% else %}
        <div class="card create-post-bar d-flex flex-column p-3">
            <img class="img-fluid d-block m-auto pb-2" src="{% static 'your-blog-logo-280x224.png' %}" width="72" height="72">
            <h3>Latest posts:</h3>
            <ul>
                {% for post in latest_posts %}
                    <p><a  href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                {% endfor %}
            </ul>
        </div>
        
        <div class="card create-post-bar d-flex flex-column p-3">
            <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
        </div>
        {% endif%}
        </div>
        </div>
    </div>
<div class="paginator">
    {% include "pagination.html" with page=object_list %}
</div>
{% else %}
<h2>No posts</h2>


{% endif %}
{% endblock %}
  